-- tables
CREATE SEQUENCE characters_seq START WITH 1;
CREATE SEQUENCE races_seq START WITH 1;
CREATE SEQUENCE casts_seq START WITH 1;
CREATE SEQUENCE religions_seq START WITH 1;
CREATE SEQUENCE skills_seq START WITH 1;
CREATE SEQUENCE skills_of_characters_seq START WITH 1;
CREATE SEQUENCE effect_seq START WITH 1;

-- histories
CREATE SEQUENCE characters_h_seq START WITH 1;
CREATE SEQUENCE races_h_seq START WITH 1;
CREATE SEQUENCE casts_h_seq START WITH 1;
CREATE SEQUENCE religions_h_seq START WITH 1;
CREATE SEQUENCE skills_h_seq START WITH 1;
CREATE SEQUENCE effect_h_seq START WITH 1;
